### ISSUE TITLE
Update codebase to correspond to eslint style

### ISSUE THREAD

**Issue by blimpich** [blimpich/bmac-warehouse#109]
This'll be a pain in the butt. The codebase currently doesn't have any sort of unified style. The .eslintrc.json in the root directory has a style but it hasn't been enforced. Hound will make sure all PRs correspond to it now, but it won't detect code that isn't in the PR diff, so we have to just go through and change it all manually at some point

**Comment by JulesChoq** [comment]
i can do this automatically but hound still doesn't seem to want to like my auto formatted stuff even though its doing it by airbnb's style guide
