### ISSUE TITLE
Sometimes Product List is filled in *very* incorrectly when editing a shipment

### ISSUE THREAD

**Issue by blimpich** [blimpich/bmac-warehouse#144]
For example, looking at shipments from around 6/17/2015 from the community foodbank of dayton, everything got right-shifted.

the funding src is being display in the unit weight column
the unit weight data is in the case lots column
and the case lots is in the total weight column

VERY WEIRD.

**Comment by JulesChoq** [comment]
these are all things that probably have to do with the scripts messing up on a few edge cases that weren't covered

**Comment by blimpich** [comment]
Yeah you're right, looks like a script issue, I'll look into it

**Comment by blimpich** [comment]
Fixed it over in the scripts repo https://github.com/WhitmanCSCapstone/bmac-warehouse-utility/commit/8b21d6a3208b8de7e599165282560db56bd47734
