### ISSUE TITLE
Invoice Date and Invoice number are null, not being assigned anywhere

### ISSUE THREAD

**Issue by therajesh** [blimpich/bmac-warehouse#67]
We need to have invoice dates and invoice numbers for each shipment, and as far as I can see there's nowhere they're being assigned, and the current data in the database doesn't include them either.

**Comment by JulesChoq** [comment]
can assign in the shipment form. do we know how we want to assign this?

**Comment by blimpich** [comment]
@therajesh can we close this issue now? is this solved?

**Comment by therajesh** [comment]
Temporary fix put in, no response for Jeff, though what we have right now is completely functional and works the way the old program did.
