### ISSUE TITLE
determine consistent signifiers for ability to edit

### ISSUE THREAD

**Issue by milloypr** [blimpich/bmac-warehouse#77]
Currently, Customers has an arrow icon for rows that indicates they are editable, while other editable objects are highlighted while hovered over. We should have a conversation about which approach makes it more clear what is editable.

**Comment by JulesChoq** [comment]
Little arrows versus no little arrows. Either way ReactTable will highlight on hover. @milloypr

**Comment by milloypr** [comment]
I've noticed that highlighting is less visible for some of the rows than others since they're different colors. I agree now that arrows would be unnecessary but it could be useful to make highlighting more visually distinct.
