### ISSUE TITLE
implement permissions for certain types of users

### ISSUE THREAD

**Issue by blimpich** [blimpich/bmac-warehouse#8]
this'll be firebasey and stuff

**Comment by JulesChoq** [comment]
PERMISSIONS
Foodbank director does everything. 
Staff products account management

Office staff: everything else. So no account management or editing staff and products. 
Restrict form access to these users.

**Comment by pablofernandezcom** [comment]
Create shipments and receipts
put in providers
run reports
edit all of them
customers


adding staff food bank director
products

**Comment by pablofernandezorg** [comment]
No not yet it’s not linked to FIREBASE

**Comment by JulesChoq** [comment]
adding roles to staff page
